packages:
  - "packages/*"
  - "apps/*"
allowBuilds:
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@langchain/langgraph@1.4.7'
